const input =
    `YYYYYYYYYYYYYYYYYYYYYYYGGGGGGGGGGGSSSSSSSSSSSSSSSSSRRRRRRRZXXXXXUUUUUUUSSRRRRRRRRRRRRRRRRRRRRRRRVVVVVSSSSSSSOOOOOOOOOOOOOOOBBPPPPPPPPPJJJJJJ
YYYDDDYYYYYYYYYYYYYYYYGGGGGGGGGGGXXSSSSSSSSSSSSSSSRRRRRRRRZXXXXUUUUUUUUUURRRRRRRRRRRRRRRRRRRRRRRRVVVGSSSSSSSOOOOOOOOOOOHOOOOPPPPPPPPPJJJJJJJ
YYYDDDDYDYYYYYYYYYYGGYGGGGGGGGGGGXSSSSSSSSSSSSSSSSZRRRZZZZZZXXXUUUUUUUUUUQRRRRRRRRRRRRRRRRRRRRRRRVDGGSSTTTTSOOOOOOOOOOOHHOOOPPPPPPPPPPJJJJJJ
YYYYYDDDDDDDDYYYYYYYGGGGGGGGGGGGGSWSSSSSSSSSSSSSSSZZZZZZZZZZZZZUUUUUUUUUUURRRRRRRRRRRRRRRRRRRRRRGGGGGSTTTTTTOOHOAOOOOOOHHHHHVVPPPPPPQQYYYYJJ
YIIDYYDDDDDDDYYYYYYYGGGGGGGGGGGGSSSSSSSSSSSNNNSNNZZZMZZZZZZZZZZUUUUUUUUUUURRRRRRRRRRRRRRRRRRRRGGGGGGGGTTTTHHHHHOAOAOOOOHNNNHVVPPPPPYQYYYYYYJ
IIIDDYYDDDDDYYYYYYYYYGGGGGGGGGGSSSSSSSSSSSSNNNNNNNZZZZZZZZZZZZUUUUUUUUUUUUUUURRRRRRRRRRRRRRRRRGGGGGGGGTTTTTHHHHOAAAOOOHHHHHHHPPPYYYYYYYYYYYY
IIIDDYDDDDDDDDYYYYYYYYGGGGGGGGGSSSSSSSSSSSNNNNNNNNNNNZZZZZZZZZUUUUUUUUUUUUUUUURRWRRRRRRRRUUGRGGGGGGGGGTTTTTHHHAAAAAOOOHHHHHHHEPPYYYYYYYYYYYY
IIIDDDDDDDDDDYYYYYYYGGGGGGGGGGGGSFSSSSSSSSSNNNNNNNNNNNZUZZZZZZZZUUUUUUUUUUUUUUYYRRRRRRRUUUUGRGGGGGGGGYTTTTTHHHHHHAAOOOHHHHHHHEEYYYYYYYYYYYYY
IIDDDDDDDDDDDYYYYYYGGGGGGGGGGGGGZFSSSSSSSSSSSSNNNNNNNNNNZZZMZZZUUUUUZZZZZZZZZZYYYYRRRRRUUUGGGGGGGGGGGTTTTHHHHHHHHAOOHHHHHHHHHEAAYYYYYYYYYYYY
IIDIIDDDDDDDDYYYYYYGGGGGGGGGGGGTFFFFSSSSSSSSSSNNNNNNNNNNZZMMZZZUUUUUZZZZZZZZZZYYYYYUUUUUUUGGGGGGGGGGHHHTTTHHOOOOOOOOOHHHHHHHHEYYYYYYYYYYYYYY
IIIIIDDDDDDDDYYYYYYYGGGGGGGGGGGGGFFFSLLSSSSSBBNCNNNNNNNNNZMZZZUUUUUUZZZZZZZZZZAAYYYAUUUUUUUUGGGGGGGGHHHHHTHHOOOORROOHHHHNHHEEEEEEYYYYYYYYYYY
IIIIIDDDDDDYDYYYYCYGGUUUGGGGGGGGGFFFFLLLFFPSSSCCCNNNNNNINNMZZPUTTTTUZZZZZZZZZZAAAAAAUUUUUUUGGGGGGGGGGBHHHRHHHHHRRROHHHHNNNNNNEEEEEEYYYYYYYYY
IIIIIIDDDDDYYYYYCCCCCCCGGGGGFFFFFFFFFFFFFFPPSCCCCNNNNNNINMDDDDUDTTTTZZZZZZZZZZAAAAXXUUUUUUUUGGGGGGBBBBHHHRRRRRRRRRRFHHNNNNNNNNEEEEEEEYFYYYYY
IIIIIIIDDDDDYYYCCRCCCCCCOOOFFFFFFFFFFFFFFFFCCCCCCCENNWWIDDDDDDDDTTTZZZZZZZZZZZAAAAXXUUUUUUUUUUGGGBOBBBBRRRRRRRRRRRFFFFNNNNNNNNNEEEEEEXYYYYQQ
IIIIDDDDDDDDDDWQCCCCCCCCCCCFFFFFFFFFFFFFFFFCCCCCCCCNJWWIDDDDDDDDTTTZZZZZZZZZZZAAAAXXUXUTTTUUUUUBNBBBBBRRRRRRRRRRRRRFFNNNNNNNNNNNCEEEEEYQQYQQ
IIIIIDDDDDDSWWWWCCCCCCCCCCCFFFFFFFFFFFFFFCCCCCCCCCCRWWWWDDDDDDDDDDVZZZZZZZZZZZAAAAXXUUUATTTUUTUBNBBBBRRRRRRRRRRRRRPNNNNNNNNNNNNNCEEEEYYYQQQQ
IIIIIIDDSSDSWWWWCCCCCCCCCCCFFFFFFFFFFFFFFCCCCCCCCCCCWWWUDDDDDDDDVVVVZZZZZZZZZZAAAAXXUUUTTTTTTTTBBBBBBBRRRRRRRRRPPPPNNNNNNNNNNNNCCCCEEEQQQYQQ
IIIIIIDDSSSSWWCCCCCCCCCCCCFFFFFFFFFFFGCCCCCCCCCCCCCWWWWWDDDDDDVVVVVVZZZZZZZZZZAAAXXXXXTTTTTTTTTBBBBBBBBRRRRORRRRPPNNNNNNNNNNNNNRCCSCEQQQQYQQ
IIIIIIDSSSSSSSSCCCCCCCCCCCFFFFFFFFFFGGGGCCCCCCCCCCCWWWVVDDDDDDDVVVVVWNNNZZZZZNAAJJJJXTTTTTTHHTTBBBBBBBBRRRRRRRRRPPPNNNNNNNNNNNRRCCCCQQQQYYQQ
IIIIIISSSSSSSSCCCCCCCCCCCZFUFFFFFFFFGGGGGCCCCCCCCCCWWWWVVVVVDDVVVVVVVNNNZZZZZNNNJJJJJTTTTTHHHBBBBBBBBBBRBRTTRRVVRPPNNNNNNNNNNPCCCCCCQQQYYYYQ
IIIIIASSSSSSSSCCCCCCCCCZZZZFFFNFNNFFGGGGGCCCCYCCCCCWWWVVVVVVVDDVVVVVVSSNZZZZZNNNJJJJJJJJTHHHHBBBBBBBBBBBBRTTRRRRRRPPNBNNNNNNNNCCCCCCQQQQQYYQ
IAIAAASSSSSSSRRCCCCCCCCZZZZNNNNNNNCCGGGCCCCCCYCCCOOOOVVVVVVVVDVVVVVVVVSNZZZZZNNNNJJJJJJPTHHHHBBBBBBBBBBBBBBBVEREEEEEBBNNNNNNNCCCCCCQQQQQQYYQ
AAAAAAASSSSSSSCCCCCCCCCCCZNNNNNNNCCCCCCCCCCCCYCOOOOOOOOOVVVVVVVVVVVVVESNZZZZZNNNJJJJJJJJHHHHHBBBBBBBEBBBBBBBVEEEEEEEGGGGYGGNCCCCCCCCCQCQQYQQ
SAAAAAAAAASSSSSCCCCCCCCKCNNNNNNNNCCCCCCCCCYYYYCOOOOOOOOOVVVVVVVVVVVEEEECZZZZZNNJJJJJJJJJJJHHHBBBBBBBBBBBBBBEEEEEEEEEEGGGGGGGGCCCCCCCCCCCQQQQ
AAAAAAAAAAASAIACCCCCCCKKKKNNNNNNNCCCCCCCCCYYYYYOOOOOOOOOVVVVVVVVVVVEEEEEZZZZZJNJJJJJJJJJJJHHHHBAABBBBBBBBBBEEEEEEEEEGGGGGGGGGCCCCCCCCCCCQQQQ
AKAAAAAAAAAAAAAYYCYCYCKTTTTNNTNNXXXCCCCCCYYYYYYOOOOOOOOOVVVVVVVVVEEEEEEEZZZZZJJJJJJJJJJJHHHHHHHBBBBBBBBBBBBBEEEEEEEEEGGGGGGGGCCCCCCCCCCCQQQQ
AAAAAAAAOOAAAAAAYYYYYCCTTTTTTTTXXXXXCYYCVYYYYYYOOOOWWWWWWWWVVVCCCCCEEEEEEJJJJJJJJJJJJJJJHHHHHHHBBBBBBBBBBBBBEEEEEEEEEGGGGGGGGGGCCCCCRRRCQQQQ
NANNAAAAOAAAAAAAYYYYYTMTTTTTTTTTXXXXXYYYYYYYYYYOOOOWWWWWWWWCCCCCCCCEEEEEETJJJJJJJJJJJJEHHHHHHHHHHBBBBBBBBBBEEEEEEEEEEGGGGGGGGGGGCCRRRRRCQQQQ
NNNNAAPPPPPAAAAAYYYYYTTTTTTTTTXXXXXXXXYYYYYYYYYOOOOWWWWWWWWCCCCCCCCCEEEETTJJTJJJJJEJJQEEEHHHHHHHBBBBBBBBBBBEEEEEEEEGGGGGGGGGGGGGBCCRRRJJJQQJ
NNNNAAPPPPPAAAAAYYYYYTTTTTTTTXXXXXXXXKKKDYYYYYYCCOOWWWWWWWWCCCCCCCCCCCCCCTTTTJJJJJEEEEEEEHHHHHHHHBBBBBBBBBBEEEEEEEEEGGGGGGGGGGGBBCCCRJJJJJJJ
NNNNNAPPPPPAAAAAYYYYTTTTTTTTTTXXXXXYKKKKYYYYYYYCCCCWWWWWWWWCCCCCCCCCCCCCTTTTTTTTJJEEEEEEEEEHHHHHBFBBBBBBBBBBEEEEEEEEEEEGGGGGGCCJJJJJJJJJJJJS
NNNNBBPPPPPAAAAPPYYYTTTTTTTTTTXXXXYYYYYKYYYYYYCCCCCWWWWWWWWWWWWCCCCCCCCCTTTTTTTTTTZEEEEEEHHHHWWHBBBBBBBBBBBBEEEEEEEEEEOOGGGGGGJJJJJJJJJJJJJS
NNNNNPPPPPPPAPPPPYYYTTTTTTTTTTXXXXXXXYYYYYYYYYCCCCOWWWWWWWWWWWWCCCCCCCCCTTTTTTTTTZZEEEEEEHWWWWWHBBBBBBBBBBBBKEEEEEEEEEOGGGGGGGGJJJJJJJJJJJJJ
NNNNNNPPPPPPAPPPPPYYYYTTTTTTTTXXXXXXXYYYYYYYYCCCCCOWWWWWWWWWWWWCACCCCCCCCTTTTTTTTEEEEEEEEEPPPWWHHHBHBBBBOOOOEEEEEEEEEOOGGGGYYYYJJJJJJJJJJJJJ
NNNNNNPPPPPPPPPPPYYYYYTTTTTTTTTMMMXMXXYYYYYYYCCYCCOWWWWWWWWWWWAAACCCQTCCTTTTTTTTTJEEEEEEQWWWWWWWHHHHHHBBOEOOSEEEEEEEEESSYYYYYYYJJJJJJJJJJJJJ
NNNNNNNNPPPPPPPPPYYYYYETTTTTTTTMMKMMMMYYYYYYYYYYCCOWWWWWWWWWWWAAACLLTTCTTTTTTTTTJJJJEEEEEWWWWWWWWHHHEEEEEEEOSSSEEEEEEESSSYYYYYYYJJJJJJJJJLLJ
NNNNYNPPPPPPPPPPPPYYEEEETTTTTTMMMMMMMMYZYYYYYGGGCCOOOOWWWWWWWWAAAATTTTTTTTTBTTTTTJJJJEWWWWWWWWWWWHHHHEDGEEEESSEEEESSESSSFSYYYYYYJJJJJJJJJLZZ
NANNYYYPPPPPPYYYYPYYEEETTTTTTTMMMMMMOOYZYYYYYGGGCCOOOOOWWWWWWWKAAATTTTTTTBBBBBBTTJJJJEWWWWWWWWWWHHHHHGGGGEESSSSSESSSSSSSSSSYYYYYYHJHHJJJJLLL
NANNYYYPPPPPPPYYYYYKEEEETTTTTMMMOMMOOYYYYYYYYKKKKCOOOOOWWWWWWWKAATTTTTTBBBBBBBBBJJJTJWWWWWWWWWWWHHHHHGGGGGGASSSSSSSSSSSSSSYYYYYYHHHHHJJJLLLL
VVEVYYYYYPPPPPYYYYYKEEEETTTTTTTMOOOOOOYFYYYYYKKKKKKKKKKWWWWWWWKKATTTTTTTBBBBBBBBJJJTJWWWWWWWWRRRRRRHHGGGGGGGSSSSSSSSSSSSSSYYYYYYHHHHJJJJLLJL
VVVVYYYYYYPYYFYYKKKKEKKTTTTTTTLMMOOOOOOYYYYYDDKKKKKKKKKWWWWWWWKKAAAZTTQQBBBBBBBBJJJTTLLLLLLLLLLRRRRHHGGGGGGGGGGSSSSSSSSSSSYYYYHYHHHHJJJJJJJJ
VVVVVYYYYYYYYFFYKKKKKKKKKKZZTGMMMMOOOOOCYCCYDDKKKKKKKKKWWWWWWWKAAZZZTTQQBBBBBBBBBBTTTLLLLLLLLLLRRRRGGGGGGGGGGGGSSSSSSSSSSSYYHHHHHHHHJJJJJFJJ
VVVVYYYYYYYFYFFFKKKKKKKKZZZWGGGMMMOOONNCCCCCDKKKKKKKKKKKKKKKAAAAZZZZTTTQBBBBBBNBBTTTTLLLLLLLLLLRRRRGGGGGGGGGGGGSSSSSSSSSFSSSHHHHHHHHHFFFJFFJ
VVVVVVFFYYFFFFFFYYKKKKKEEEZWWGGMMNNNNNFFCCCCDKKKKKKKKKKKKKKKKAAZZZZZZTQQBBBBBNNBBTTTTLLLLLLLLLLRRRRRGGGGGGGGGGGSSSSSSSFFFFSGHHHHHHHHHFFFFFFJ
VVVVVFFFFFFFFFFFKKKKKKKEEEEEEEEEENNNNNFNNCVVVVVVKKKKKKKCCKKKKKAZZZZZZZQBBBBBBNNBTTTTTLLLLLLLLLLRRRRRGGGGGGGGGGSSSSSSLFFFFFFGHHHHHHHHHHFFFFFF
VVVVVFFFFFFFFFFFKKKKKKKEEEEEEEEEENNNNNNNNVVVVVVVVVKYCCKCCCCZKSZZZZZZZZZTTBBBBBBTTTTTTLLLLLLLLLLRRRRRAGGGGGGGGGSSLLLLLFFFFFFFFHHHHHHHHHHFFFFF
VVVVVFFFFFFFFFFKKKKKKKKEEEEEEEEEENNNNVNNNVVVVVVVVVKKKCCCCCZZZZZZZZZZZZZZTBBBTTTTTTTTTLLLLLLLLLLRRRRYNGNNGGGGGSSLLLLLLLFFFFFFFFHHHHHHHHFFFFFF
VVVVVVFFFFFFFFFKKKLLLLLLEEEEEEEEENNNNVNVVVQVVVVVVVCCCCCCCCZZZZZZZZZZZZZZBBBTTTTTTTTTTLLLLLLLLLLRMMNNNNNNNGGGGGGLLLLLLLLLFFFFFFHHHHHHHHFFFFFZ
VVVVVVFFFFFFFFFKKELLLLLLEEEEEEEEEWWNNVVVQQQQQVVCVVCCCCCCZCZZZZZZZZZZZZZZPBBZTTTTTTTTPLLLLLLLLLLMMNNNNNNNNGGGGGGGGGGLLLLLLLFFFFFHHHHHHHFFFFZZ
VVVVVVFFFFFFFFNNKELLLLLLEEEEEEEEEWWWNVVVQQQQQVVCFFCCCCCCZZZZZZZZZZZZZZPPNZZZZTTTTTTTTLLLLLLLLLLMMMNNNNNNNNGGGGGGGGGLLLLLLLFFOAFFHZHZZHFFFFZZ
VVVVVFFFFFFFFFNNZELLLLLLEEEEEEEEEWFFVVVVQQQVVVCCCCCCCCCCZZZZZZZZZZZZZZGPNZZZZTTTTTTTTTPPPYYYYMMMMNNNNNNNNNNNNGGGGLLLLLLLLLFAAAFFHZZZZZZZFZZZ
VVVVVFFFFFFFNNNLLLLLLLLLLEEEEEEEEFFFVVVVVVQKKVCCCCCCCCCCZZZZZZZZZZZZZZGNNZZZZTTTTTTTTYOPMMYYYYMMMNNNNNNMNMMMMMMGGLLLLLLLLLAAAAAAAAZZZZZZZZZZ
VVVFFFFFFFFFNNNLLLLLLLLLLEEEEEWWWFFVVVVVVVQQKVCKCKCCCCCCCZIIZIZZZZFZZGGGNGZZTTTTSTTTTOOOMYYYYYMMMNNMNNMMMMMMMMMLLLLLLLLLLLAAAAAAAAAZAZZZZZZZ
VVVVVVFFFFFNINNLLLLLLLLLLEEEEEWWDFFFFTTVTTTTKKKKKKCCCCCCCCIIIAZZZZFFZGGGGGZZTTTSSSTTTOOMMYYYMYMMMNMMNNNMMMMMMMWOLLLLLLLLLLAAAAAAAAAAAZAZZZZZ
VVVVVVFFJJJNNNNLLLLLLLLLLLEEEEWDDFFFTTTTTTCTKKKKKCCCCCCCCCCAIAAZZZFFFFFFFGTTTTOSOOOQOOOOMMMYMYMMMMMMMMMMMMMIIMWWLWWWWWWLLAAAAAAAAAAAAAAZZZZZ
VVVVVVVFJLLLLLLLLLLLLLLLLLEWWWWDDFFFTTTTTTCTKKKKKKCDBCCCCAAAAAAAAFFFFFEFFFTTTTOOOOOOOOOOMMMMMMMMMMMMNMMMMMMMIIIWWWWWWWLLAAAAAAAAAAAAAAAZZZZZ
VVVVVVVFVLLLLLLLLLLLLLLLLLEWWWWWDFXXTTTTTTTKKKKKKDDDDCCCCCBBAAAFFFFFFEEEEFFFMCOOOOOOOOOOOMMMMMMLLLNNNNNNNNRNIIIWWWWWWWWAAAAAAAAAAAAAHAWWZZZZ
VVVVVVVVVLLLLLLLLLLLLELLLEEWWWWWWYXYTTTTTTTTKKKKKKDDDDDCDBBAAAAFFFFFEEEZEFFFMOOOOOOOOOOOOMMMMKKLLNNNSNNNNNNNNNNWWWWWWWWAAAAAAAAAAAAAAAWWZZWZ
VVVVVVVVXLLLLLLLLLLLLELLLEENWWYYYYYYTSTTTTTKKKKKKHIDDDDDDBAAAAAAFAFFEEEEYMMMMMNNOOOOOOOOOXMMKKKLLLNNNNNNNNNNNNWWWWWWWWWWAAAAAAAAAAAAAAWWWWWZ
VVVVVVVVWLLLLLLLLLLLLJLLLNNWWWWYYYYYYYTTTTTKKKKKHHHDDDDDDBAAAAAAAAEFEEEMMMMMMMMMOOOOOOOOXXXXOKKKKLLLNNNNNNNNNWWWWWWWWWWAAAAAAAAAAAAAWWWWWWZZ
VVVVVVWWWLLLLLLLLLLLLJLLLNWWWWWYYYYYYTTTTTOOOOOKHHHHDDDDKAAAAAAAAZEEEEEMMMMMMMMMMOOOOOOOYXBKKKKKKLLNNNNNNNNNNWWWWWWWWWWAAAAAAAAAAAAWWWWWWWWW
VVAVVVWWWWWWWLLLLLLLLJLLLRWRWWWYYYYYYYTTTFOOOOOOOHHNBBDDAAAAAAAAAEEEEEEERMMMMMMMMOOOOOXOXXXKKKKKKLLLNNNNNNMWWWWWWWWWWWWWWDDDAAAAWWWWWWWWWWWZ
AAADVVWWVWWWWWJJJJJJJJJNRRRRRRYYYYYYYYTTFFTOOOOOONNNBBDAAAAAAAAAAWEEEEEMMMMMMMMMMMOOOOXXXXXKKKKKKNNNNNNNNMMWWWWWWWWWWWWWWWDAAWWWWWWWWWWWWWZZ
AAAAAAAAWWWWWWWWWJJJJJJRRRRRRRRYYYYYYYTTTTTTOOOODBBBBBBBAAAAAAAARWEEEEEMMMMMMMMMMMMXXXXXXXOKKKKKKKKNNNNNNNYWYYWWWWWWWWWCWDDWAWWWWWWWWWWWWWWZ
AAAAAAAAZWWWWWWWJJJJJJJRRRRRRRRRYYYYYYYGGTKKKOOBBBBBBBBBAAAHHAARRRRRRRRMMMMMMMMMMMMXXXXXXXOKKKKKKKKENNNNNNYYYYWWWWWWWWWWWWDWWWWWWWWWWWWWWWZZ
AAAAAAAAWWWWWWWWJJJJRRRRRRRRRRRRYRRRYYYGGGGOOOOBBBBBBBBBBAHAAASRSRRRRRRMMMMMMMMMMMMMXXXXXXXXXKKKKKKKNNYYNYYYYWWWWWWWWWWWWDDWWWWWWWWWWWWWWWWW
AAAAAAIAAWWWWWWWJJJJJRRRRRRRRRRFFRRFGGGGGGGPPPBBBBBBBBBBBHHHHHSRSRKRRRRRRMMMMMMMMMMMMMXXXXXXXKKKKKKKKYYYYSSSSDFWWWWWWWWZRDWWWWWWWWWWWWWZZWWW
AAAAAAAAAAWWWWWWJJJJJRRRRRRRRRRFFRFFGGGGGGGPPPPBBBBBBJBBBHHHHHSSSRRRRRRRRRMMMMMMMMMMXXXXXXXXXXKKKKKKKYYYDSSSSDFFFFRWRWZZRJJWJWWWWWWWWWWWZZZZ
AAAAAAAAAWWWWWWWJJJJJRRRRRRRRFFFFFFFFGGGGGGGGPPBBBBBBBBBBHHHHHSSRRRRRRRRRRRRRMMMMMMMXXXXXXXXKKKKKKKKKSSSSSSSSDFRRRRRRWRRRRJJJWWJWWWWWWWWWZZZ
ZZAAAAAAAWZWWWWWWJJJRRRRRRRRRFFFFFFFFGGGGGPPPPPBBBBBBBBHBHHHHHRRRRRRRRRRRRRRRMMMMMTMXXXXXXXXKKKKKKKYKSSSSSSSSDDDRRRRRRRRRRRRJJJJJWWJJJJWZZZZ
ZZAAAAAAAWZZWWWWWWJJRRRRRRRFFFFFFFFFGGGGGGGGPPPPBBBBBBBHHHHHHHHRRRRRRRRRRRRRRMMMXXXXXXXXXXXXXXKKKKKYYSSSSSSSSDDDDRRRRRRRRRRRRJJJJJJJJJJZZZZZ
ZZZAZZAAZZZZZWWJJJJJRRRRRRFFFFFFFFFFFFGGGGGPPPPBBBBBBBPHHHHHHHHHRRRRRRRRRRRRRRRRXXXXXXXXXXXXXXKKKKYYYSSSSSSSSDDDDEEERRRRRRRRRRJJJJJJJJJZZZZZ
ZZZZZZAAZZZZZWJJJJJJJRJRRRJFFFFFFFFFFGGGGPPPPPPBBBBBBBBHHHHHHHRRRRRRRRRRRRRRRROXXXXXXXXXXXXXXXXXXXXYYYDDDSSSSDDDDEEERRRRRRRRRJJJJJJJJJJZZZZZ
ZZZZZZZAZZZZZWJJJJJJJRRRRRJJJFDFFFFFBGGGWWWPPWPBBBBBHHHHHHHHHHHRRRRRRRRRRRRRRROOXXXXXXXXXXXXXXXXXXYYYYDSSSSSSDDDDEEEERRRRRRLLLLLLJJJJJJZZZZZ
ZZZZZZZZZZZZZWWJJJJJJJJRRRJJJFFFFFFBBGWWWWWWPWWBRBBBBBHHHHHHHHHRRRRRRRRRRRRRRROOXXXXXXXXXXXXXXDDDDDDYYDSSSSSSDDDEEEEERRERRRLLLLLLJJJJJJZZZZZ
ZZZZZZZZZZZZZWPPPPJJJJJJJJJJJJFFGFFFFFWWWWWWWWWRRBBBBBHHHHEEHHHRHHRRRNRNNVRRVVVVVVXXXXXXXXXXXXXDDDDDDFFSSSSSSDDEEEEEEEEERRLLLLLLLLLLLLJZZZZZ
ZZZZDDDZZZZZZWPPPKJJJJJJJJJJJGGGGGFFIIIWWWWWXWWWBBBBBBHHHHEEHHHHHHRRRNNNNVVVVVVVVVYYXXXXXXPOXXXDDDDDDDFSSSSSSDFFFEEEEEEELRLLLLLLLLLLLLZZZZZZ
ZZZDDDZZZZZQQPPPPKJJJJJJJJJJJJJGGGGIIIIWWWWWWWWWBBBBBBQQQEEHHHHHHKKRNNNNJVVVVVVVVYYXXXXXXKPOOODUUUUUUUUSSSSSSFFFEEEEEEEELRLLLLLLLLLLLLJZZZZZ
ZZZZDDZZZZZQPPPPPPJJJJJJJJJJJJGGGGGIIIIWWWWWWWAWJBBBBBQQQEEEUHHKKKNRRNNNNNLVVVVVVYYXXXPPPPPPOODUUUUUUUUSSSSSSFIFEEEEEEEELLLLLLLLLLLLLLZZZZZZ
ZZDDDDRRZPPPAPPPPPPPPPPPJJJJJJGGGGGGGIIWWWWWWWAWWFBBMMEEEEEEEHHKKNNNNNNNNNNVRVVVVVXXWXPPPPPPPOOUUUUUUUUSSSSSSIIEEEEEIEEEILLLLLLLLLLLLLZZZZZZ
ZDDDDDDRPPPPPPPPPPPPPPPPJJJXXJXXGGGGXPPPWWWWWWAAAFFFMMEEEEEEEHDNNNNNNNNNNNWVVVVVVVWXWPPPPPPPPPOUUUUUUUUSSSSSSIIIIIIIIIIIILLLLLLLLLLLLLZZZZZZ
DDDDDDDDBPPPPPPPPPPPPPPPJJJJXXXXXGGGXMPPWWWWWWAAAAFMMMMEEEEEEEENNNNNNNNNNNWWVWVWVWWWWPPPPPPPPOOUUUUUUUUSSSSSSIIIIIIIIIIIILLLLLLLLLLLLLZZZZZZ
DDDDDDDDDPPPPPPPPPPPPPPPJJJJXXXXXXGMMMRPPWWWWAAAAMMMMMMMMEEEEEEXNNNNNNNNNWWWWWWWWWWPPPPPPPPPPPPUUUUUUUUUUUUUUUIIIIIIIIIIILLLLLZZJZZJZZZZZZZZ
DDDDDDDDDYDPPPPPPPPPPPPPJJXXXXXXXXXPMMXWWWWWWAMCAMMMMMMMMEEEEEXXXNNNNNNNGGWWWWWWFWWWPPPPPPPPPPPUUUUUUUUUUUUUUUIIIIIIIIIIIIILLLLZZZZZZZZZZZZZ
DDDDDDDDDDDPPPPPPPPPPPPPJXXXXXXXXXXXKXXWWWWWWWWCMMMMMMMMMEEEEEEXXXNNNNNGGGGWWWFFFFFWPPPPPPPPPPPUUUUUUUUUUUUUUUIIIIIIIIIIIIMMMMMMZZZZZHHZZZZZ
DDDDDDDDDDDPPPPPPPPPPPPPJXXXXXXXXXXXXXXWXWWWWWWCCCMMMMMMMMEEEEEXXXNGGGNGGGGGWWFFFFFFFPPPPPPPPPPUUUUUUUUKFUUUUUIIIIIIIIIMIMMMMMMZZZZZZHHHHHHZ
DDDDDDDDDDTHPCPPPPPPPPXXXXXXXXXXXXXXXXXWXXXXXXXCCCCMMMMHHHEEEEEXXXFGGGGGGGGGGFFFFFFFFPFPPPPPPPIUUUUUUUUKFUUUUUIIIIIIIIIMMMMMMMMMMMZZHHHWHHHH
DDDDDDDDDDDHHHPPPPIPPPXXXXXXXXXXXXXXXXXXXXXXXXXCCCCMMHMHHHHEEEEXFFFGGGGGGGGEEEFFFFFFFFFPPPPPPPIIIUUUUFKKKUUUUUIIIIIJIEIMMMMMMMMMMMMMFHHHHHHH
DDDDDDDDDHHHHHHPIIIIIIXXXXXXXXXXXXXXXXXXXXXCCCCCCCCMMHHHHHHHHHFFFFFFGGGGGGEEEEFFFFFFFFFPPPPPPPPIIUUUUKKKKKKKKIIIMIMMIIMMMMMMMMMMMMMMHHHHHHHM
DDDDDDDDDHHHHHPPPIIIIIXXJJXXXXXXXHXXXXXXXXXCCCCCCCCVAHHHHNNNNNNNNNNFGGGGGXKEEEFFFFFFFFFPPPPBIIIIIUUUUKKKKKKKKMMMMIIMMMMMMMMMMMMMMMMMHHHHHHHH
DDDDDDDDDHHHHHIIIIIIIIXXOOOXXXXXXHHRQXXXXXGCCCCCCCCAAAHHHNNNNNNNNNNNNNNGIKKKEEFFFFFFFFFFFPCIIIIIIUUUUKKKKKKKKKMMMBMMMMMMMMMMMMMMMHHHHHHHHHHH
DDDDDDDDHHHHHHHHHHIIIIIOOOOXXXXXXHRRQXXXXXGCCCCCCCCCAAAAHNNNNNNNNNNNNNNKKKKKKFFJJFFFFFFFFNIIIIIIIUUUUKKKKKKKMMMMBBBBBMMMMMMMMDMMHHHHHHHHHHHH
DZDDDDDHHHHHHHHHHHHIIIIIOOOOXXOOOHRRRRXXXXCCCCCCCCCAAAAAANNNNNNNNNNNNNNKKKKKKKFFJFFFFFFFFNNNIIIIIKKKKKKKKKKKMMMBBBBBBBMMMMDDVDMMHHHHHHHHHHHH
HZDDHDDHHHHHHHHHHIIIIIIIOOOOOOOOOORRRXXXNCCCCGCCCCCAAAAAANNNNNNNNNNNNNNKKKKKKKKKKOOOFFFFNNNNIIIIIIKKKKKKKKKKMMMBBBBBBBMMMMDDDDDDDDDDHHHHHHHH
HHHHHLLHHHHHHHHIHIIIIIIIOOOOOOOOOORMRRXXXCCCCCCCCCAAAAAAANNNNNNNNNNNNNNKKKKKKKKKJOOFFFFFNNNNIIIIIIIKKKKKKKKKMMMBZBBBBMMMMMDDDDDDDDDHHHHHHHDH
BBBHAHHHHHHHHHHIIIIIIIQQOOOOOOOOOOOMRQQQCCCCCCCCCAAAAAAAANNNNNNNNNNFFFKKKKKKKKJJJOFFFFFFFFNCCIIIIKKKKKKKKKMMMMMBBBBBBMMMDDDDDDDDDDDHHHHHHDDD
BBBHHHHHHHHHHHIIIIIIIPIQQOOOOOOOOORRRQQQCCCCCCCCCCCAAAAAANNNNNNNNNNFFJJKJKKKKJJFFFFFFFFFFFNCCCCIIIKKKKKKKKKKMLBBBBBBBBBTDDDDDDDDDDDHHHHHDDDD
BBBBBBHHHHHHHHHIIIIIIIIQQQOOQOQQQQQQQQQQCCCCCCCCCCCCAAAAANNNNNNNNNNJJJJJJKJKKJJJSFFFFFFFFFFFCCIIIKKKKKKKKKKKMLLLLBBBBBBBDDDDDDDDDDDDDDDDDDDD
BBBBBBBBHHIIIHIIIIIIIIIQQQQOQOQQQQQQVQCCCCCCCCCCCCCCAAAAANNNNNNNNNNJJJJJJJJJJJJJFFFFFFFFJFFFCCICIIIIKKUKKKKKLLLLLBBBBBBDDDDDDDDDDDDDDDDDDDDD
BBBBBBNHHNNIIIIIIIIITTQQQQQQQQQQQQVVVCCCCCCCCCCCCCCCAAAAAAAAAARRRRRJJJJJJJJJJJJJFFFFFFFFFFCCCCCCIIIUUUUKKKKLLLLLLLBBBBBZDDDDDDDVVDVDDDDDDDDD
BBBBBNNNNNNNNIIIIIIITTTQQQQQQQQQQVVVVVVVCCCCCCCCCCCXXAAAAAAAARRRRRJJJJJJJJJJJJJJPPFFFFFFWFCCCCCCCCCVVUUUUUUULLLLLLLLBKBDDDDDDDVVVDVVDDDVDDDD
BBBBNNNNNNNNIIIIIIIITTTTHHQQQQQQQQVVVVVVVVVCCCCCCCCCXAAAAAAARRRRRRRRJJJJJJJJJJJJPFFPPFFFCCCCCCCCCCCVVVMMUUULLLLLLLLLLLLDDDDDVVVVVVVVVVVVDDDD
BNNNNNNNNNNIIIIIIIIITTTTTHQQQQQQQVVVVVVVVVVVCVVCCCCKKKAAAAAAAARRKRRRJJJJJJJJJJJJPPFFPFFFCCCCCCCCCCRMMMMMUUUUULLLLLLLLLLLYDDVVVVVVVVVVVVVVVDD
BNNNNNNNNNNENIIIIIITTTTTTHQHQQQQQVVVVVVVVVVVVVVCVVCKKKKKKAAGKKKKKRRJJJJJJJJJJJJJJPPPPFFCCCCCCCCCCCMMMMMMMBMUMMLLLLLLLLYYYDYYVVVVVVVVVVVVVVDD
BNNNNNNNNNNNNIIIIIIIITTTTHHHHYYQQQQVVVVVVVVVVVVVVVCCKKKKKKAKKKKKKRRJJJJJUUJJJJJJJJPPPPFCCCCCCCCCCCMMMMMMMBMMMKLLLLDDDDDDDDYYVVVVVVVVVVVVVDDD
BNBBNNNNNNNNNNIIIIIIIIFTHHHYYYYQQQQVVVVVVVVVVVVVVVCCVVKKKKKKKKKKKRRRUUUJUUUJJJJJPPPPPXTCCCCCCCCCEMMMMMMMMMMMBLLLLLDDDDDDDDYVVVVVVVVVVVVVVVDD
BBBBNNNNNNNNNNIIIIIIIIFFHHHHHHQQQQLLLLLVLVVVVVVVVVVVVKKKKKKKKKKKKRUUUUUUUUUJJJJJJPXXXXTTCCCCCCCCCMMMMMMMMMMMBLLLLLDDDDDDDDYVVVVVVVVVVVVVVVVV
BBBBBNNNNNNNNNIINIIIIIFHHHHHHQQQQQQLLLLLLVVVVVVVVVVKKKKVKKKKKKKKKKJUUUUUUUUJJJJJJPPPXXXTCCCCCCCCCCMMMMMMMMMBBLLLJLDDDDDDDDYSSVVVVVUVVVVVVVVV
BBBNNNNNNNNNNNNNNNIIIFFHJJJJJJJJJJQLLLLLLLVVVVVVVVVVVKKKKKKKKKKKKUUUUUUUUUUUULLLJPLXXXXXAACCCCCCCCMMMMMMMMMBLLLLLLDDDDDDDDSSVVVVVVUVVVVVVVVC
BBBNNNNNNNNNNNNNNRRRFFFHJJJJJJJJJJLLLLLLLLVVVVVVVVVVKKKKKKKKKKKKKUUUUUUUUUUUUULLLLLXXXXXXACCCCCDCCAMMMMMMMMMLLSSLLDDDDDDDDSVVVVVVUUVVUCCUCCC
BBBNNNNNNNNNNNNNRRRRRHHHJJJJJJJJJJLLLLLLLJJVVVVVVVVKKKKKKKKKKKKKKUUUUUUUUUUUUULLLLXXXXXXXAACEEEUUUUUMUUMMMUUULUSSSDDDDDDDDDDVVVVVUUUVUCCUCCC
BBBBYYNNNNNNNNNNRRRRRRHHJJJJJJJJJJLLLLLLLJGTGVVVVVKKKKKKMKKKKKKKUUUUUUUUUUUUUULLLLXXXXXAAARRRREUUUUUUUUUUUUUUUUUSSSSSSSDDDDDVEVVVUUUUUUUUUCC
BBBBBYNNNNNNNNNCFRRCRRHAJJJJJJJJJJLLLLGGGGGGGJKVKKKKMMMMMKKKKKKKUUUUUUUUUUUUUULLLLLXXXXAARRRRUUUUUUUUUUUUUUUUUUUSSSSSSSDDDDDEEVVUUUUUUUUCCCC
BYYYYYYYNNNNNNNCCCCCRRRHJJJJJJJJJJLLLGGGGGGGGGKVKKKKMMMMMMMMKKKKUUUUUUUUUUUUUUUXXXXXXXXRRRRRRRUUUUUUUUUUUUUUUUSSSSSSSSSDDDDDEEVIUUUUUUUUUUCC
BYYYYYYYYYYNNNNCCCCCCRRRJJJJJJJJJJLLLWGWGGGGGKKKKMMKKMMMMMMMMKKKUUUUUUUUQUUUUUUXXXXXXXXXXRRRRRUUUUUUUUUUUEEUUUSSSSSSSSSSSSSSSEUUUUUUUUUUUUUC
BYYYYYYYYYXONNNCCCCCCCRRJJJJJJJJJJLWWWWWGGGGKKKKKMMKMMMMMMMMMMKKUUUUUUUQQQQUUXXXXXXXXXXRRRRRRRRRRUUUUUUUUEEUEUSSSSSSSSSSSSMMMUUUUUUUUUUUUUUU
YYYYYYYYOOOONNCCCCCCCDDDDDGJJJJJJJLWWWWGGCCCKKKKKKMMMMMMMMMMMKKKKSUUUXEEEEEENXEXXXXXXXXRRRRRRRRRUUUUUUUEUUEEEEESSESESSSMMMMMMMMUUUUUUUUUUUUG
YYYYYYYYOOOOOCCCCCCCCDDDCCGJJJJJJJWWWWWWWWCCCKKKKMMMMMMMMMMMMKKKKSSUXXEEEEENNEEEEXXXXXRRRRRRRRRRUUUEEEEEEEEEEEEESEEEEMMMMMMMMMMUUUUUUUUUUUUG
GYYYYYYXOOOOOOCCCCCCCCDDCCGGGGGGGGWWWWWWWWWCCKKFKMMMMMMMMMMMMMKKKKSSEEEEEEEEEYEEXXXXXRRRRRRRRRRRUUEEEEEEEEEEEEEEEEEEMMMMMMMMMMMUUUUUUUUUUUGG
GYYYOTYOOOOOOSOCCCCCCCCCCCGGGGGGGWWWWWWWWWCCZZZFFMDMMDDDDMMWWKKKRLLEEEEEEEEEEEEEXXXXXXXXRRRRRRJJUJJJJEEEEEEEEEEEEEEEMMMMMMMMMFUUUUUUUUUUUUGG
GGGOOOOOOOOOOOOOCCCCCCCCCCCCGGGGGGWWWWWWWCCCZZZFDADDMMDDDMWWLLKKKLLEEEEEEEEEEEEEEEXXXXRRRRRRRRRJJJJJJEEEEEEEEEEEEEEMMMMMMMMMMFGGGGGUGUUUJJJG
GGGGOOOOOOOOOOOOCCCCCCCCGGGGGGGGGGWWWWWEZZZZZZZFDDDMMDDDDDDLLLKKLLLEEEEEEEEEEEEEEEEXXRRXRRRRRRRRRJJJJJJEEEEEEEEEEEEEEMMFFFFFFFGGGGGGGUGGJJGG
GGGOOOOOOOOOOOCCCCCCCCCCCGGGGGZGGZWWWWWEZZZZZZZDDDDDDDDDDDULLLLKLLLLEEEEEEEEEEEMEXEXXXXXRLRRRRRRRJJJEJENNEEEEEEEEEEEEMMFFFFFFFFGGGGGGGGGJGGG
GGGGOOOOOOOOOOOCCCCCCCCCGGGGGGZZZZZWWWWWZZZZZZZZDDDDDDDDDDUULLLLLLLEEEEEEEEEEEEEXXEXXXXXXXRRRRRMEEEJEEENEEEEEEEEEEEEEMMFFFFFFAAGGGGGGGGGGGGG
GOGGOOOOOOOOOOOOCCCCCCCCGGGGGGGGZZZWWWWEZZZZZZZDDKDKDDDDDDLLLLLLLLEVEEEEEEEEEEEEXXXXXXGGXGGYGRMMEEEEEEEEEEPEEEEEEEEELFFFFFFFFFAGGGGGGGGGGGGG
OOOOOOOOOOOOOOOOCCCCCCTCGGGGGGGZZZZWWWZZZZZZZZZZDKKKDDDEEEELLLLLLLEEEEEEEEEEERRXXXXXXXXGGGGGGBEEEEEEEEEEEEEEEEEEYEEEEEFFFFFFFYGGGGGGGGGGGGGG
QQOOOOOOOOOOOOOTTTCTTCTCTGGGGGZZZZZZWWZZZZZZZZZZKKVVVHDCEEKLLLLLCCCECECEEEEEERUUNMMMMMGGGGGXEEEEEEEEEEEEEEEEEEEEYEFFFFFFFFFFGGGGGGGGGGGGGGGG
QKOOOOOOOOOOTOTTTTTTTTTTTGGGGGZZZZZZZZZZZZZZZZZZZVVVVVVCEEEEEEEECCCECCCCEEEEEUUUNNMMMMMMGGGXXEEEEEEEEEEEEEEEUEEEEEFFFFFFFFFFFGGGGGGGGVGGGGGG
QKKOOOOOOOTTTTTTTTTTTTTTTTTTTWWZZZZZZZZZZZZZZZZZMVVVVVVVVEEEEECEUCCCCCCCEUNEUUUUUUMMMMMGGGXXXLLEEEEEEEEEEEEEEMMZZZFZFFFFFFFFFGGGGGGGGGGLGGGG
QKKKKKKKKTTKTTTTTTTTTTTTTTTTPWZZZZZZZZZZZZZZZPZHVVVVVVVVVEEEEVCCCCCCCCCCEUUUUUUUUMMMMMMGXXXXLLLEEEEEEEEEEEEEMMZZZZZZFFFFFFFFFGGGGGGGGGGGGGGG
KKKKKKKKKKTTTTTWWTWTTWWTTTTTTWZZZZZZZZZZZZVPQPHPPVVVEVVVEEEEEEEECCCCCCCCCCUUUUUUUFFFMMMWMXLLLLLLLLEEEEEEEEEMMZZZZZZZFFFFFFFFFGGNGGGGGGGGGGGG
KKKKKKKKKKTTTTTWWWWWWWWWTTTTWWZZZZZZZZZPPPPPPPPPPEVVEVEEEEEEEECCCCCCCCCCCCUMUUUUUUMMMMMMMLLLLLLLLLLEEEEEEEMMMMZBZZZZZZFFFFFFFFFGGGGGGGGGGGGG
KKKKKKKKKKTTTTTWWWWWWWWWWWWWWWWZZZZZZZZPPPPPPPPPPEEEEEEEEEEEEECCCCCCCCCCCCUMMUUUUUMMMMMLLLLLLLLLLLLLEEEEEEEEMMZZZZZZZZZFFFFFFFFFGGGGGGGGGGGG
VKKKKKKKKKTTWWWWWWWWWWWWWWWWWWWWZZZZZZZPPPPPPPPPPEEEEEEEEEEEECCCCCCCCCCCCCMMMMUMUUFFMMMLLLLLLLLLLLLLEEEEEEMMMZZZZZZZZZZFFFFFFFFFGGGGGGGGGGGG
KKKKKKWWWTTWWWWWWWWWWWWWWWWWWWWWZZWWWZZPPPPPPPPPEEEEEEEEEEEEEECCCCCCCCCCCCCMMMMMOFFFMLLLLLLLLLLLLLLAEEEEEEMMMMZZZZZZZZFFFLLLFFFFGGGGGGGGGGGI
KKKKKKKWWWWWWWWWWWWWWWWXWWWWWWWWWWWWWWPPPPPPPPPPEEEEEEEEEEEEEEEECCCCCCCCCCCCCMMMOFFFMLJLLLLLLLLLLLLAAAVMEEEMMMMZZZZZZZZFFLLLFFFFFFGGGGGGGIGI
KKKKKKWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWPPPPPPPPEEEEEEEEEEEEEEEEEECCCCCCCCCCOOMOOOFOOMJJLLLLLLLLLLLLLAVVVVMMMMMZZZZZZZZFFELLLLFFFFFFGGGIGIIII
KKKKKWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWPWPPPPPEEEEEEEEEEEEEEEEEEECCCCCCCFCCOOOOOOOOOOJJLLLLLLLLLVVLLAVVVVMMMMMZZZZZZZZZFELLLLFFFFFIIGGIIIIII
KKKKWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWPDDPEEEEEEEEEEEEEEEEEEEECCCCCCFCXOOOOOOOOOJJJJLLVLLVVLVLLLVVVVVMMMMMMMMZZZZZZZEELLLFFFFIIIIIIIIIII
KKKWWWWWWWWWWWWWWWWWWWXWWWWWWWWWWWWWWWWWWWWWWWWEEEEEEEEEEEEEEEEEEECCCCCCCNOOOOOOOOOOJJJJJLVVVVVVVVVVVVVVVMMMMMMMMMMZZZZEEEEELFFIIIIIIIIIIIII`;

const part1 = (input: string) => {
    const lines = input.split('\n');
    const map = lines.map(it => it.split(''));
    // y -> row
    // x -> col 

    //  map regionId to set of points
    const regions: {
        [regionId: string]: Set<string>;
    } = {};

    // map point to regionId
    const pointToRegion: {
        [point: string]: string;
    } = {};

    const allPoints = map.flatMap((row, rowIndex) => {
        return row.map((col, colIndex) => {
            return { row: rowIndex, col: colIndex, value: col };
        });
    });

    const registerPoint = (row: number, col: number, regionId: string) => {
        if (!regions[regionId]) {
            regions[regionId] = new Set<string>();
        }
        regions[regionId].add(`${row}-${col}`);
        pointToRegion[`${row}-${col}`] = regionId;
    }

    const searchForSiblings = (row: number, col: number, regionId: string, regionValue: string) => {
        console.log('searchForSiblings', row, col, regionId, regionValue);

        const value = map[row][col];
        if (value !== regionValue) {
            return;
        }

        registerPoint(row, col, regionId);

        if (map[row + 1]?.[col] && !pointToRegion[`${row + 1}-${col}`]) {
            searchForSiblings(row + 1, col, regionId, regionValue);
        }
        if (map[row]?.[col + 1] && !pointToRegion[`${row}-${col + 1}`]) {
            searchForSiblings(row, col + 1, regionId, regionValue);
        }
        if (map[row - 1]?.[col] && !pointToRegion[`${row - 1}-${col}`]) {
            searchForSiblings(row - 1, col, regionId, regionValue);
        }
        if (map[row]?.[col - 1] && !pointToRegion[`${row}-${col - 1}`]) {
            searchForSiblings(row, col - 1, regionId, regionValue);
        }
    }

    allPoints.forEach(({ row, col, value }) => {
        if (pointToRegion[`${row}-${col}`]) {
            return;
        };
        // let's create a region for this point and let's explore all the points that are connected to this point
        let regionId = String(Object.keys(regions).length + '-' + value);
        registerPoint(row, col, regionId);
        searchForSiblings(row, col, regionId, value);
    });





    const printRegions = () => {
        for (const key in regions) {
            const [id, char] = key.split('-');
            const mapOfRegion = regions[key];
            const tempMap = map.map(it => it.map(() => '.'));
            for (const point of mapOfRegion) {
                const [row, col] = point.split('-').map(Number);
                tempMap[row][col] = char;
            }
            const tempMapStr = tempMap.map(it => it.join('')).join('\n');
            console.log(`Region:${char}:\n`+tempMapStr);
        }
    }

    printRegions();

    const getSiblings = (row: number, col: number) => [
        [row - 1, col],
        [row + 1, col],
        [row, col - 1],
        [row, col + 1]
    ];

    function replaceDashes(text: string) {
        return text.replace(/-+/g, function(match) {
            let length = match.length;
            return '-' + ' '.repeat(length - 1);
        });
    }


    function replaceLines(text: string) {
        return text.replace(/\|+/g, function(match) {
            let length = match.length;
            return '|' + ' '.repeat(length - 1);
        });
    }
    const getSides = (region: Set<string>) => {
        const points = region.values().toArray().map(it => it.split('-').map(Number)).map(([row, col]) => [row * 2 + 2, col * 2 + 2]);
        let canvas = new Array(map.length * 2 + 4).fill(0).map(() => new Array(map[0].length * 2+ 3).fill('.'));

        points.forEach(([row, col]) => {
            canvas[row][col] = '#';
            // top
            canvas[row - 1][col] = '*';
            // bottom
            canvas[row + 1][col] = '*';
            // left
            canvas[row][col - 1] = '*';
            // right
            canvas[row][col + 1] = '*';

            // top left
            canvas[row - 1][col - 1] = '*';
            // top right
            canvas[row - 1][col + 1] = '*';
            // bottom left
            canvas[row + 1][col - 1] = '*';
            // bottom right
            canvas[row + 1][col + 1] = '*';
        });


        let print = canvas.map(it => it.join('')).join('\n');
        const show = () => {
            // console.log((print));
        }


        print = print.replaceAll('.*', '.|').replaceAll('*.', '|.');

        canvas = print.split('\n').map(it => it.split(''));
        // rotate canvas 
        canvas = canvas[0].map((_, colIndex) => canvas.map(row => row[colIndex]));

        print = canvas.map(it => it.join('')).join('\n');
        print = print.replaceAll('.*', '.-').replaceAll('*.', '-.');

        canvas = print.split('\n').map(it => it.split(''));
        // rotate canvas
        canvas = canvas[0].map((_, colIndex) => canvas.map(row => row[colIndex]));
        print = canvas.map(it => it.join('')).join('\n');

        print = replaceDashes(print);

        canvas = print.split('\n').map(it => it.split(''));
        // rotate canvas
        canvas = canvas[0].map((_, colIndex) => canvas.map(row => row[colIndex]));
        print = canvas.map(it => it.join('')).join('\n');

        print = replaceLines(print);
   
        show();
        return print.split('').filter(it => it === '|' || it === '-').length;
    }

    let total = 0;
    for (const regionId in regions) {
        const region = regions[regionId];
        const area = region.size;
        const perimeter = region.values().toArray().reduce((acc, point) => {
            const [row, col] = point.split('-').map(Number);
            const siblings = [
                `${row - 1}-${col}`,
                `${row + 1}-${col}`,
                `${row}-${col - 1}`,
                `${row}-${col + 1}`
            ];
            return acc + siblings.filter(it => !region.has(it)).length;
        }, 0);

        const sides = getSides(region);
        console.log('Region:', regionId, 'Area:', area,/*  'Perimeter:', perimeter,  */'sides', sides);
        total += area * sides;
    }
    console.log('Total:', total);
}


part1(input);